branches:
  only:
    - dev
    - master
language:
  - java
jdk:
  - openjdk6
before_install:
  # environment info
  - mvn -version
  - gradle -v
  - uname -a
  # required libs for android build tools
  - if [ `uname -m` = x86_64 ]; then sudo apt-get update; fi
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  # for gradle output style
  - export TERM=dumb
  # newer version of gradle
  - wget http://services.gradle.org/distributions/gradle-1.11-bin.zip
  - unzip -qq gradle-1.11-bin.zip
  - export GRADLE_HOME=$PWD/gradle-1.11
  - export PATH=$GRADLE_HOME/bin:$PATH
  # just to test gradle version, against our provided one
  - gradle -v
  # newest android SDK 22.6.1
  - wget http://dl.google.com/android/android-sdk_r22.6.1-linux.tgz
  - tar -zxf android-sdk_r22.6.1-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # manually set sdk.dir variable, according to local paths
  - echo "sdk.dir=$ANDROID_HOME" > local.properties
  - echo yes | android update sdk -a -t tools,platform-tools,extra-android-support,extra-android-m2repository,android-19,build-tools-19.0.3 --force --no-ui
